/* Opt-in actual Chromium integration against a disposable COPY of a real store.
 * Usage: MODELING_REVIEW_QA_STORE=/path/to/real/test/store node .../review_ui_qa.cjs
 * Requires locally installed playwright and Chromium; installs nothing.
 */
'use strict';
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const source = process.env.MODELING_REVIEW_QA_STORE;
if (!source) throw new Error('Set MODELING_REVIEW_QA_STORE to a real generated test store; no mocked API data is used');
const output = process.env.MODELING_REVIEW_QA_OUTPUT || '/tmp/review-ui-qa';
fs.mkdirSync(output, { recursive: true });
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'review-ui-copy-'));
const store = path.join(temp, 'project');
fs.cpSync(source, store, { recursive: true });
fs.rmSync(path.join(store, 'review'), { recursive: true, force: true });
let server, browser;
(async () => {
  server = spawn(process.env.PYTHON || 'python', ['-m', 'experimental_modeling.review_server', '--store', store, '--port', '0'], { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] });
  const origin = await new Promise((resolve, reject) => {
    let buffer = ''; const timer = setTimeout(() => reject(new Error('Local server startup timeout')), 15000);
    server.stdout.on('data', data => { buffer += data; const found = buffer.match(/Local model review: (http:\/\/127\.0\.0\.1:\d+)/); if (found) { clearTimeout(timer); resolve(found[1]); } });
    server.on('error', reject); server.on('exit', code => { if (!buffer.includes('Local model review:')) reject(new Error(`Server exited ${code}`)); });
    server.stderr.on('data', data => process.stderr.write(data));
  });
  browser = await chromium.launch({ ...(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {}), headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage(); const pageErrors = []; page.on('pageerror', error => pageErrors.push(error.message));
  await page.goto(origin); await page.locator('#revision-title').filter({ hasText: 'Revision r3' }).waitFor();
  await page.locator('#geometry-stats').filter({ hasText: '9 parts' }).waitFor();
  assert.equal(await page.locator('#accept-submit').isEnabled(), true);
  assert.equal(await page.locator('#part-list button').count(), 9);
  assert.ok(await page.locator('#requirements .requirement').count() >= 5);
  assert.equal(await page.locator('#render-list img').count(), 4);
  await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
  const initialCanvas = await page.locator('#model-canvas').evaluate(canvas => canvas.toDataURL());
  await page.locator('#model-canvas').press('ArrowRight');
  await page.waitForFunction(before => document.getElementById('model-canvas').toDataURL() !== before, initialCanvas);
  await page.locator('#compare-mode').click(); assert.equal(await page.locator('#before-pane').isVisible(), true);
  await page.locator('#part-list button').filter({ hasText: 'cargo tray' }).click();
  assert.equal(await page.locator('#part-list button[aria-pressed=true]').count(), 1);
  await page.locator('#wireframe').click(); assert.equal(await page.locator('#wireframe').getAttribute('aria-pressed'), 'true');
  await page.locator('#reset-view').click();
  await page.screenshot({ path: path.join(output, 'desktop-compare.png'), fullPage: true });
  await page.locator('#current-mode').click();
  await page.locator('#accept-notes').fill('QA: disposable copied-store acceptance, browser interaction and persistence test.');
  await page.locator('#accept-submit').click(); await page.locator('#accepted-status').filter({ hasText: 'Human decision recorded' }).waitFor();
  assert.equal(await page.locator('#accept-submit').isEnabled(), false);
  const prompt = 'QA: preserve all geometry. Queue persistence test only; do not execute source.';
  await page.locator('#request-prompt').fill(prompt); await page.locator('#request-submit').click(); await page.locator('#queue-count').filter({ hasText: '1' }).waitFor();
  await page.locator('#request-prompt').fill(prompt); await page.locator('#request-submit').click(); await page.locator('#request-submit:not([disabled])').waitFor();
  assert.equal(await page.locator('#queue-count').innerText(), '1');
  await page.reload(); await page.locator('#accepted-status').filter({ hasText: 'Human decision recorded' }).waitFor();
  assert.equal(await page.locator('#queue-count').innerText(), '1');
  await page.locator('.queue-item summary').click(); assert.equal(await page.locator('.queue-item p').innerText(), prompt);
  await page.getByRole('button', { name: 'bad Checks failed', exact: true }).click(); await page.locator('#revision-title').filter({ hasText: 'Revision bad' }).waitFor();
  await page.locator('#verified-status').filter({ hasText: 'One or more checks failed' }).waitFor(); assert.equal(await page.locator('#accept-submit').isEnabled(), false);
  await page.getByRole('button', { name: 'r0 Machine verified', exact: true }).click(); await page.locator('#geometry-stats').filter({ hasText: '9 parts' }).waitFor(); assert.equal(await page.locator('#compare-mode').isEnabled(), false); assert.equal(await page.locator('#accept-submit').isEnabled(), true);
  await page.getByRole('button', { name: 'r3 Human accepted', exact: true }).click(); await page.locator('#accepted-status').filter({ hasText: 'Human decision recorded' }).waitFor();
  await page.locator('#revision-title').scrollIntoViewIfNeeded(); await page.screenshot({ path: path.join(output, 'desktop-review.png'), fullPage: true });
  const project = await (await context.request.get(origin + '/api/project')).json();
  const revision = await (await context.request.get(origin + '/api/revisions/r3')).json();
  const badCSRF = await context.request.post(origin + '/api/requests', { headers: { Origin: origin }, data: { csrf_token: 'invalid', revision_id: 'r3', expected_result_hash: revision.revision.result_hash, prompt } }); assert.equal(badCSRF.status(), 403);
  const stale = await context.request.post(origin + '/api/requests', { headers: { Origin: origin }, data: { csrf_token: project.csrf_token, revision_id: 'r3', expected_result_hash: '0'.repeat(64), prompt } }); assert.equal(stale.status(), 409);
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  const phone = await mobile.newPage(); phone.on('pageerror', error => pageErrors.push(error.message)); await phone.goto(origin); await phone.locator('#geometry-stats').filter({ hasText: '9 parts' }).waitFor();
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await phone.screenshot({ path: path.join(output, 'mobile-review.png'), fullPage: true });
  await phone.locator('#compare-mode').click(); assert.equal(await phone.locator('#before-pane').isVisible(), true); await phone.screenshot({ path: path.join(output, 'mobile-compare.png') });
  await phone.locator('#request-prompt').fill('QA mobile saved request; no execution.'); await phone.locator('#request-submit').click(); await phone.locator('#queue-count').filter({ hasText: '2' }).waitFor();
  const protectedObservation = path.join(store, 'accepted', 'r2', 'inspection', 'observation.json');
  const originalObservation = fs.readFileSync(protectedObservation); fs.appendFileSync(protectedObservation, ' ');
  await page.getByRole('button', { name: 'r2 Machine verified', exact: true }).click();
  await page.locator('#notice').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#accept-submit').isEnabled(), false);
  assert.equal(await page.locator('#preview-empty').isVisible(), true);
  assert.equal(await page.getByRole('button', { name: 'r2 Evidence unavailable', exact: true }).count(), 1);
  await page.screenshot({ path: path.join(output, 'desktop-integrity-error.png'), fullPage: true });
  fs.writeFileSync(protectedObservation, originalObservation);
  await page.getByRole('button', { name: 'r2 Evidence unavailable', exact: true }).click();
  await page.getByRole('button', { name: 'r2 Machine verified', exact: true }).waitFor();
  assert.equal(await page.locator('#preview-empty').isVisible(), false);
  await page.getByRole('button', { name: 'r3 Human accepted', exact: true }).click();
  await page.locator('#accepted-status').filter({ hasText: 'Human decision recorded' }).waitFor();
  assert.deepEqual(pageErrors, []);
  server.kill('SIGTERM'); await new Promise(resolve => server.once('exit', resolve));
  await page.getByRole('button', { name: 'r1 Machine verified', exact: true }).click(); await page.locator('#notice').waitFor({ state: 'visible' }); assert.equal(await page.locator('#accept-submit').isEnabled(), false); assert.equal(await page.locator('#download-glb').isVisible(), false); assert.equal(await page.locator('#preview-empty').isVisible(), true);
  assert.equal(await page.getByRole('button', { name: 'r1 Evidence unavailable', exact: true }).count(), 1);
  const summary = { status: 'passed', browser: await browser.version(), viewport_desktop: [1440, 1100], viewport_mobile: [390, 844], actual_server: true, mocked_api: false, tested: ['real inspected mesh and material render', 'orbit keyboard changes canvas', 'before/after', 'part highlighting', 'edges/reset', 'saved image artifacts', 'human acceptance persistence', 'repeat queue deduplication', 'queued request history after reload', 'failed revision acceptance disabled', 'initial revision applicability', 'CSRF/stale-hash rejection', 'mobile no horizontal overflow', 'mobile queue submission', 'tampered artifact clears preview and blocks acceptance', 'real server outage clears prior revision and disables actions'], screenshots: ['desktop-compare.png', 'desktop-review.png', 'mobile-review.png', 'mobile-compare.png', 'desktop-integrity-error.png'], store_copy: store };
  fs.writeFileSync(path.join(output, 'summary.json'), JSON.stringify(summary, null, 2) + '\n'); console.log(JSON.stringify(summary, null, 2));
})().catch(error => { fs.writeFileSync(path.join(output, 'summary.json'), JSON.stringify({ status: browser ? 'failed' : 'browser_launch_blocked', error: error.message.slice(0, 1000), desktop_mobile_verified: false }, null, 2) + '\n'); console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); if (server && server.exitCode === null) server.kill('SIGTERM'); });
