/* Actual watering-can browser regression against a disposable COPY of the
 * locked-requirement project emitted by run_review_project.py. No mocked API.
 * MODELING_REVIEW_QA_STORE=/path/to/project node review_water_ui_qa.cjs
 * Uses the CI-pinned Playwright browser; optional CHROMIUM selects an executable.
 */
'use strict';
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const source = process.env.MODELING_REVIEW_QA_STORE;
if (!source) throw new Error('Set MODELING_REVIEW_QA_STORE to the real watering-can project generated by run_review_project.py');
const output = process.env.MODELING_REVIEW_QA_OUTPUT || '/tmp/review-water-ui-qa';
fs.mkdirSync(output, { recursive: true });
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'review-water-ui-copy-'));
const store = path.join(temp, 'project');
fs.cpSync(source, store, { recursive: true });
// Only the fresh disposable copy is reset. Machine reports remain unchanged.
fs.rmSync(path.join(store, 'review'), { recursive: true, force: true });
let server, browser;
const screenshots = [];
(async () => {
  server = spawn(process.env.PYTHON || 'python', ['-m', 'experimental_modeling.review_server', '--store', store, '--port', '0'], { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] });
  const origin = await new Promise((resolve, reject) => {
    let buffer = '';
    const timer = setTimeout(() => reject(new Error('Local watering-can review server startup timeout')), 15000);
    server.stdout.on('data', data => {
      buffer += data;
      const match = buffer.match(/Local model review: (http:\/\/127\.0\.0\.1:\d+)/);
      if (match) { clearTimeout(timer); resolve(match[1]); }
    });
    server.on('error', error => { clearTimeout(timer); reject(error); });
    server.on('exit', code => { if (!buffer.includes('Local model review:')) { clearTimeout(timer); reject(new Error(`Server exited ${code}`)); } });
    server.stderr.on('data', data => process.stderr.write(data));
  });
  browser = await chromium.launch({ ...(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {}), headless: true });
  const desktop = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  desktop.setDefaultTimeout(90000);
  desktop.setDefaultNavigationTimeout(90000);
  const page = await desktop.newPage();
  const pageErrors = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  const snapshot = async (name, target = page) => {
    await target.screenshot({ path: path.join(output, name), fullPage: true });
    screenshots.push(name);
  };
  const revision = async id => {
    const response = await desktop.request.get(`${origin}/api/revisions/${encodeURIComponent(id)}`, { timeout: 90000 });
    assert.equal(response.status(), 200, `Real report for ${id} must be readable`);
    return response.json();
  };
  const requirement = (target, title) => target.locator('#requirements .requirement').filter({ has: target.locator('summary').filter({ hasText: title }) });
  const expand = async (target, title) => {
    const row = requirement(target, title);
    assert.equal(await row.count(), 1, `Unique visible requirement: ${title}`);
    if (await row.getAttribute('open') === null) await row.locator('summary').click();
    await row.locator('.requirement-details').waitFor({ state: 'visible' });
    await row.scrollIntoViewIfNeeded();
    return row;
  };

  // Initial page fetch recomputes genuine geometry evidence for all revisions.
  await page.goto(origin, { waitUntil: 'domcontentloaded', timeout: 90000 });
  await page.locator('#revision-title').filter({ hasText: 'Revision r2' }).waitFor({ timeout: 90000 });
  await page.locator('#geometry-stats').filter({ hasText: '2 parts' }).waitFor({ timeout: 90000 });
  await page.locator('#verified-status').filter({ hasText: 'Recorded checks passed' }).waitFor();
  assert.equal(await page.locator('#accepted-status').innerText(), 'Awaiting your decision');
  assert.equal(await page.locator('#accept-submit').isEnabled(), true);
  assert.equal(await page.locator('#part-list button').count(), 2);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  const r2 = await revision('r2');
  assert.equal(r2.report.machine_verified, true);
  assert.equal(r2.state.human_accepted, false);
  assert.equal(Object.keys(r2.observation.parts).length, 2);
  const water = r2.report.requirements.find(row => row.id === 'water_passage');
  assert.ok(water && water.status === 'pass' && water.measured !== null);
  const passage = await expand(page, water.title);
  assert.ok((await passage.innerText()).includes('Measured'));
  assert.ok((await passage.innerText()).includes('Expected'));
  const image = await page.locator('#model-canvas').evaluate(canvas => canvas.toDataURL());
  await page.locator('#model-canvas').press('ArrowRight');
  await page.waitForFunction(before => document.getElementById('model-canvas').toDataURL() !== before, image);
  await page.locator('#compare-mode').click();
  assert.equal(await page.locator('#before-pane').isVisible(), true);
  await page.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
  await page.locator('#revision-title').scrollIntoViewIfNeeded();
  await snapshot('water-desktop.png');

  await page.getByRole('button', { name: 'r0 Machine verified', exact: true }).click();
  await page.locator('#revision-title').filter({ hasText: 'Revision r0' }).waitFor();
  await page.locator('#geometry-stats').filter({ hasText: '2 parts' }).waitFor();
  const r0 = await revision('r0');
  const unknown = r0.report.requirements.filter(row => row.status === 'unknown');
  assert.equal(unknown.length, 2, 'Only the two revision-only preservation requirements are unknown for the initial build');
  assert.deepEqual(unknown.map(row => row.id).sort(), ['protected_body_rays', 'protected_body_region']);
  assert.ok(unknown.every(row => row.hard === true && row.applicable === false));
  assert.equal(r0.report.machine_verified, true);
  assert.equal(await page.locator('#verified-status').innerText(), 'Recorded checks passed');
  assert.equal(await page.locator('#accept-submit').isEnabled(), true, 'Non-applicable hard checks must not block initial acceptance');
  assert.equal(await page.locator('#compare-mode').isEnabled(), false);
  assert.equal(await page.locator('#requirement-summary .unknown').innerText(), '2 unknown');
  for (const row of unknown) {
    const visible = await expand(page, row.title);
    assert.ok((await visible.innerText()).includes('Not applicable to this revision; excluded from required checks.'));
  }
  await page.locator('#revision-title').scrollIntoViewIfNeeded();
  await snapshot('water-initial.png');

  await page.getByRole('button', { name: 'bad-body Checks failed', exact: true }).click();
  await page.locator('#revision-title').filter({ hasText: 'Revision bad-body' }).waitFor();
  await page.locator('#geometry-stats').filter({ hasText: '2 parts' }).waitFor();
  await page.locator('#verified-status').filter({ hasText: 'One or more checks failed' }).waitFor();
  const bad = await revision('bad-body');
  assert.equal(bad.revision.status, 'rejected');
  assert.equal(bad.report.machine_verified, false);
  assert.equal(bad.state.human_accepted, false);
  const inspected = bad.report.requirements.find(row => row.id === 'pipeline-inspect');
  assert.equal(inspected.status, 'pass');
  assert.equal(inspected.measured.exit_code, 0, 'Inspection succeeded despite failed preservation');
  const failures = bad.report.requirements.filter(row => ['protected_body_region', 'protected_body_rays'].includes(row.id));
  assert.equal(failures.length, 2);
  assert.ok(failures.every(row => row.status === 'fail' && row.hard === true && row.applicable === true));
  assert.equal(await page.locator('#built-status').innerText(), 'Inspected geometry available');
  assert.equal(await page.locator('#accept-submit').isEnabled(), false);
  for (const row of failures) {
    const visible = await expand(page, row.title);
    assert.ok((await visible.innerText()).includes('Measured'));
    assert.ok((await visible.innerText()).includes('Expected'));
    assert.ok((await visible.innerText()).includes('Evidence'));
  }
  await page.locator('#revision-title').scrollIntoViewIfNeeded();
  await snapshot('water-negative.png');

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  mobile.setDefaultTimeout(90000);
  const phone = await mobile.newPage();
  phone.on('pageerror', error => pageErrors.push(error.message));
  await phone.goto(origin, { waitUntil: 'domcontentloaded', timeout: 90000 });
  await phone.locator('#geometry-stats').filter({ hasText: '2 parts' }).waitFor();
  assert.equal(await phone.locator('#revision-title').innerText(), 'Revision r2');
  assert.equal(await phone.locator('#accept-submit').isEnabled(), true);
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'Mobile page must not overflow horizontally');
  await phone.locator('#compare-mode').click();
  assert.equal(await phone.locator('#before-pane').isVisible(), true);
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  await phone.waitForFunction(() => [...document.images].every(img => img.complete && img.naturalWidth > 0));
  await snapshot('water-mobile.png', phone);
  assert.deepEqual(pageErrors, []);

  const summary = {
    status: 'passed', browser: await browser.version(), actual_server: true, mocked_api: false,
    viewport_desktop: [1440, 1100], viewport_mobile: [390, 844],
    source_fixture: 'run_review_project.py watering-can locked requirements', store_copy: store,
    verified: {
      r2_machine_verified: true, r2_human_accepted: false, semantic_parts: 2,
      r0_unknown_hard_nonapplicable: 2, r0_accept_enabled: true,
      negative_inspection_succeeded: true, negative_preservation_failed: failures.map(row => row.id),
      negative_machine_verified: false, negative_accept_disabled: true,
      measured_evidence_expanded: true, keyboard_orbit_changed_canvas: true,
      desktop_mobile_no_horizontal_overflow: true
    }, screenshots
  };
  fs.writeFileSync(path.join(output, 'water-summary.json'), JSON.stringify(summary, null, 2) + '\n');
  console.log(JSON.stringify(summary, null, 2));
})().catch(error => {
  fs.writeFileSync(path.join(output, 'water-summary.json'), JSON.stringify({ status: browser ? 'failed' : 'browser_launch_blocked', error: error.message.slice(0, 1500), desktop_mobile_verified: false, screenshots }, null, 2) + '\n');
  console.error(error); process.exitCode = 1;
}).finally(async () => {
  if (browser) await browser.close();
  if (server && server.exitCode === null) server.kill('SIGTERM');
});
